server:
  port: 8888

spring:
  datasource:
    mysql:
      name: dev
      jdbc-url: jdbc:mysql://localhost:3306/pro_dev?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  application:
    name: wechatapp

  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 101.200.58.119
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
## mybatis
mybatis:
  mapper-locations: classpath:/*.xml
  type-aliases-package: com.wechatapp.entity

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
  # 默认false,当为true时，自动检验适合的数据库
  auto-dialect: true
  # 这个一定要加上，不然mysql和oracle分页两个只能用一个，另一个会报错，加上后，两中数据库分页都可以用了
  auto-runtime-dialect:

## jwt
appacc:
  jwt:
    # 加密秘钥
    secret: f8e2e52034348f86b67cde581c0f9eb5asdfeqwr
    # token有效时长，7天，单位秒
    expire: 267840000
    header: token

